import React, { useEffect, useState } from 'react';
import { Head, Link, usePage } from '@inertiajs/react';
import MaintenanceLayout from '@/Layouts/MaintenanceLayout';
import useFixFlowSettings from '@/hooks/useFixFlowSettings';

export default function Show({ invoiceId }) {
    const { language } = useFixFlowSettings();
    const user = usePage().props.auth.user;
    const isAdmin = user.role === 'admin';

    const [invoice, setInvoice] = useState(null);
    const [loading, setLoading] = useState(true);
    const [updating, setUpdating] = useState(false);

    const text = {
        th: {
            layoutTitle: 'รายละเอียดใบแจ้งหนี้',
            back: 'กลับรายการใบแจ้งหนี้',

            invoice: 'ใบแจ้งหนี้',
            invoiceNo: 'เลขที่ใบแจ้งหนี้',
            issuedDate: 'วันที่ออกเอกสาร',

            requester: 'ผู้แจ้ง',
            technician: 'ช่างผู้รับผิดชอบ',
            requestNo: 'เลขที่งานซ่อม',
            requestTitle: 'หัวข้องานซ่อม',
            location: 'สถานที่',

            invoiceDetails: 'รายละเอียดค่าใช้จ่าย',
            description: 'รายการ',
            quantity: 'จำนวน',
            unitPrice: 'ราคาต่อหน่วย',
            subtotal: 'รวม',

            laborCost: 'ค่าแรง',
            partsCost: 'ค่าอะไหล่',
            totalAmount: 'ยอดรวมทั้งหมด',

            paymentStatus: 'สถานะการชำระเงิน',
            unpaid: 'ยังไม่ชำระ',
            paid: 'ชำระแล้ว',
            cancelled: 'ยกเลิก',
            paidAt: 'ชำระเมื่อ',
            method: 'ช่องทาง',
            reference: 'เลขอ้างอิง',
            promptpay: 'พร้อมเพย์',
            card: 'บัตรเครดิต/เดบิต',
            awaitingPayment: 'รอผู้แจ้งชำระเงินผ่านระบบ สถานะจะเปลี่ยนเป็นชำระแล้วโดยอัตโนมัติ',
            payNow: 'ชำระเงิน',
            cancelInvoice: 'ยกเลิกใบแจ้งหนี้',
            cancelConfirm: 'ยืนยันการยกเลิกใบแจ้งหนี้นี้?',

            note: 'หมายเหตุ',
            noNote: 'ไม่มีหมายเหตุ',

            saveStatus: 'บันทึกสถานะ',
            saving: 'กำลังบันทึก...',
            print: 'พิมพ์ใบแจ้งหนี้',

            updateSuccess:
                'อัปเดตสถานะการชำระเงินสำเร็จ',
            updateError:
                'ไม่สามารถอัปเดตสถานะได้',

            loadError:
                'ไม่สามารถโหลดข้อมูลใบแจ้งหนี้ได้',
            loading: 'กำลังโหลดข้อมูล...',
            notFound: 'ไม่พบใบแจ้งหนี้',

            printTitle: 'ใบแจ้งหนี้ค่าบำรุงรักษา',
            companyName: 'FixFlow Maintenance System',
            paymentLabel: 'สถานะการชำระเงิน',

            customerInfo: 'ข้อมูลผู้แจ้ง',
            maintenanceInfo: 'ข้อมูลงานซ่อม',

            summary: 'สรุปค่าใช้จ่าย',

            generatedBy:
                'เอกสารนี้สร้างจากระบบ FixFlow Maintenance System',
        },

        en: {
            layoutTitle: 'Invoice Details',
            back: 'Back to Invoices',

            invoice: 'Invoice',
            invoiceNo: 'Invoice Number',
            issuedDate: 'Issued Date',

            requester: 'Requester',
            technician: 'Technician',
            requestNo: 'Repair Request No.',
            requestTitle: 'Repair Title',
            location: 'Location',

            invoiceDetails: 'Invoice Details',
            description: 'Description',
            quantity: 'Qty.',
            unitPrice: 'Unit Price',
            subtotal: 'Subtotal',

            laborCost: 'Labor Cost',
            partsCost: 'Parts Cost',
            totalAmount: 'Total Amount',

            paymentStatus: 'Payment Status',
            unpaid: 'Unpaid',
            paid: 'Paid',
            cancelled: 'Cancelled',
            paidAt: 'Paid at',
            method: 'Method',
            reference: 'Reference',
            promptpay: 'PromptPay',
            card: 'Credit/debit card',
            awaitingPayment: 'Waiting for the requester to pay online. The status changes to paid automatically.',
            payNow: 'Pay now',
            cancelInvoice: 'Cancel invoice',
            cancelConfirm: 'Cancel this invoice?',

            note: 'Note',
            noNote: 'No note',

            saveStatus: 'Save Status',
            saving: 'Saving...',
            print: 'Print Invoice',

            updateSuccess:
                'Payment status updated successfully',
            updateError:
                'Unable to update payment status',

            loadError:
                'Unable to load invoice',
            loading: 'Loading invoice...',
            notFound: 'Invoice not found',

            printTitle: 'Maintenance Invoice',
            companyName: 'FixFlow Maintenance System',
            paymentLabel: 'Payment Status',

            customerInfo: 'Requester Information',
            maintenanceInfo: 'Maintenance Information',

            summary: 'Cost Summary',

            generatedBy:
                'Generated by FixFlow Maintenance System',
        },
    };

    const t = text[language] ?? text.th;

    const loadInvoice = async () => {
        setLoading(true);

        try {
            const response = await axios.get(
                `/api/maintenance/invoices/${invoiceId}`
            );

            setInvoice(response.data);
        } catch (error) {
            console.error(error);
            alert(t.loadError);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        loadInvoice();
    }, [invoiceId]);

    const cancelInvoice = async () => {
        if (!confirm(t.cancelConfirm)) {
            return;
        }

        setUpdating(true);

        try {
            await axios.put(
                `/api/maintenance/invoices/${invoiceId}`,
                {
                    payment_status: 'cancelled',
                }
            );

            await loadInvoice();
        } catch (error) {
            console.error(error);
            alert(error.response?.data?.message ?? t.updateError);
        } finally {
            setUpdating(false);
        }
    };

    const paymentText = {
        unpaid: t.unpaid,
        paid: t.paid,
        cancelled: t.cancelled,
    };

    const paymentClass = {
        unpaid:
            'bg-amber-50 text-amber-700 ring-1 ring-inset ring-amber-200',

        paid:
            'bg-emerald-50 text-emerald-700 ring-1 ring-inset ring-emerald-200',

        cancelled:
            'bg-rose-50 text-rose-700 ring-1 ring-inset ring-rose-200',
    };

    const formatMoney = (value) => {
        return Number(value || 0).toLocaleString(
            language === 'en' ? 'en-US' : 'th-TH',
            {
                minimumFractionDigits: 2,
                maximumFractionDigits: 2,
            }
        );
    };

    const formatDate = (value) => {
        if (!value) return '-';

        return new Date(value).toLocaleDateString(
            language === 'en' ? 'en-US' : 'th-TH',
            {
                day: '2-digit',
                month: 'long',
                year: 'numeric',
            }
        );
    };

    const handlePrint = () => {
        if (!invoice) return;

        const items = invoice.items ?? [];

        const itemRows =
            items.length > 0
                ? items
                      .map(
                          (item) => `
                    <tr>
                        <td>${item.description ?? '-'}</td>
                        <td class="center">${item.quantity ?? 1}</td>
                        <td class="right">฿${formatMoney(item.unit_price)}</td>
                        <td class="right">฿${formatMoney(item.subtotal)}</td>
                    </tr>
                `
                      )
                      .join('')
                : `
                    <tr>
                        <td>${t.laborCost}</td>
                        <td class="center">1</td>
                        <td class="right">฿${formatMoney(invoice.labor_cost)}</td>
                        <td class="right">฿${formatMoney(invoice.labor_cost)}</td>
                    </tr>
                    <tr>
                        <td>${t.partsCost}</td>
                        <td class="center">1</td>
                        <td class="right">฿${formatMoney(invoice.parts_cost)}</td>
                        <td class="right">฿${formatMoney(invoice.parts_cost)}</td>
                    </tr>
                `;

        const printWindow = window.open(
            '',
            '_blank',
            'width=1000,height=800'
        );

        if (!printWindow) {
            return;
        }

        printWindow.document.write(`
<!DOCTYPE html>
<html lang="${language === 'en' ? 'en' : 'th'}">
<head>
    <meta charset="UTF-8">
    <title>${invoice.invoice_no}</title>

    <style>
        @page {
            size: A4;
            margin: 14mm;
        }

        * {
            box-sizing: border-box;
        }

        body {
            margin: 0;
            color: #0f172a;
            background: #ffffff;
            font-family:
                Arial,
                "Noto Sans Thai",
                "Tahoma",
                sans-serif;
            font-size: 13px;
            line-height: 1.5;
        }

        .page {
            width: 100%;
        }

        .header {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            padding-bottom: 22px;
            border-bottom: 2px solid #0f172a;
        }

        .brand {
            font-size: 27px;
            font-weight: 800;
        }

        .brand-subtitle {
            margin-top: 4px;
            color: #64748b;
            font-size: 12px;
        }

        .invoice-title {
            text-align: right;
        }

        .invoice-title h1 {
            margin: 0;
            font-size: 25px;
            font-weight: 800;
        }

        .invoice-number {
            margin-top: 5px;
            color: #475569;
        }

        .grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 18px;
            margin-top: 22px;
        }

        .box {
            border: 1px solid #e2e8f0;
            border-radius: 10px;
            padding: 15px;
        }

        .box-title {
            margin-bottom: 10px;
            font-size: 12px;
            font-weight: 700;
            color: #64748b;
            text-transform: uppercase;
        }

        .row {
            display: flex;
            justify-content: space-between;
            gap: 15px;
            margin-top: 7px;
        }

        .label {
            color: #64748b;
        }

        .value {
            font-weight: 600;
            text-align: right;
        }

        table {
            width: 100%;
            margin-top: 24px;
            border-collapse: collapse;
        }

        th,
        td {
            border-bottom: 1px solid #e2e8f0;
            padding: 11px 10px;
        }

        th {
            background: #f8fafc;
            font-size: 11px;
            text-align: left;
            color: #475569;
        }

        .center {
            text-align: center;
        }

        .right {
            text-align: right;
        }

        .summary {
            width: 340px;
            margin-left: auto;
            margin-top: 18px;
        }

        .summary-row {
            display: flex;
            justify-content: space-between;
            padding: 7px 0;
        }

        .summary-total {
            margin-top: 6px;
            padding-top: 12px;
            border-top: 2px solid #0f172a;
            font-size: 17px;
            font-weight: 800;
        }

        .status {
            display: inline-block;
            margin-top: 18px;
            padding: 7px 12px;
            border-radius: 20px;
            background: #f1f5f9;
            font-weight: 700;
        }

        .note {
            margin-top: 24px;
            border: 1px solid #e2e8f0;
            border-radius: 10px;
            padding: 15px;
        }

        .footer {
            margin-top: 34px;
            padding-top: 14px;
            border-top: 1px solid #e2e8f0;
            text-align: center;
            color: #94a3b8;
            font-size: 11px;
        }

        @media print {
            body {
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }
        }
    </style>
</head>

<body>
    <div class="page">

        <div class="header">

            <div>
                <div class="brand">FixFlow</div>

                <div class="brand-subtitle">
                    ${t.companyName}
                </div>
            </div>

            <div class="invoice-title">

                <h1>${t.printTitle}</h1>

                <div class="invoice-number">
                    ${t.invoiceNo}: ${invoice.invoice_no}
                </div>

                <div class="invoice-number">
                    ${t.issuedDate}: ${formatDate(invoice.issued_at)}
                </div>

            </div>

        </div>


        <div class="grid">

            <div class="box">

                <div class="box-title">
                    ${t.customerInfo}
                </div>

                <div class="row">
                    <span class="label">${t.requester}</span>
                    <span class="value">
                        ${invoice.request?.requester?.name ?? '-'}
                    </span>
                </div>

                <div class="row">
                    <span class="label">Email</span>
                    <span class="value">
                        ${invoice.request?.requester?.email ?? '-'}
                    </span>
                </div>

            </div>


            <div class="box">

                <div class="box-title">
                    ${t.maintenanceInfo}
                </div>

                <div class="row">
                    <span class="label">${t.requestNo}</span>
                    <span class="value">
                        ${invoice.request?.request_no ?? '-'}
                    </span>
                </div>

                <div class="row">
                    <span class="label">${t.requestTitle}</span>
                    <span class="value">
                        ${invoice.request?.title ?? '-'}
                    </span>
                </div>

                <div class="row">
                    <span class="label">${t.location}</span>
                    <span class="value">
                        ${invoice.request?.location ?? '-'}
                    </span>
                </div>

                <div class="row">
                    <span class="label">${t.technician}</span>
                    <span class="value">
                        ${invoice.request?.technician?.name ?? '-'}
                    </span>
                </div>

            </div>

        </div>


        <table>

            <thead>
                <tr>
                    <th>${t.description}</th>
                    <th class="center">${t.quantity}</th>
                    <th class="right">${t.unitPrice}</th>
                    <th class="right">${t.subtotal}</th>
                </tr>
            </thead>

            <tbody>
                ${itemRows}
            </tbody>

        </table>


        <div class="summary">

            <div class="summary-row">
                <span>${t.laborCost}</span>
                <strong>
                    ฿${formatMoney(invoice.labor_cost)}
                </strong>
            </div>

            <div class="summary-row">
                <span>${t.partsCost}</span>
                <strong>
                    ฿${formatMoney(invoice.parts_cost)}
                </strong>
            </div>

            <div class="summary-row summary-total">
                <span>${t.totalAmount}</span>
                <span>
                    ฿${formatMoney(invoice.total_amount)}
                </span>
            </div>

        </div>


        <div class="status">
            ${t.paymentLabel}:
            ${paymentText[invoice.payment_status] ?? invoice.payment_status}
        </div>


        ${
            invoice.note
                ? `
                    <div class="note">
                        <strong>${t.note}</strong>
                        <div style="margin-top: 6px;">
                            ${invoice.note}
                        </div>
                    </div>
                `
                : ''
        }


        <div class="footer">
            ${t.generatedBy}
        </div>

    </div>

    <script>
        window.onload = function () {
            setTimeout(function () {
                window.print();
            }, 250);
        };
    </script>

</body>
</html>
        `);

        printWindow.document.close();
    };

    if (loading) {
        return (
            <MaintenanceLayout title={t.layoutTitle}>
                <div className="flex min-h-[500px] items-center justify-center">

                    <div className="flex flex-col items-center gap-3">

                        <div className="h-10 w-10 animate-spin rounded-full border-4 border-slate-200 border-t-blue-600" />

                        <span className="text-sm text-slate-500">
                            {t.loading}
                        </span>

                    </div>

                </div>
            </MaintenanceLayout>
        );
    }

    if (!invoice) {
        return (
            <MaintenanceLayout title={t.layoutTitle}>

                <div className="rounded-2xl border border-rose-200 bg-rose-50 p-5 text-rose-700">
                    {t.notFound}
                </div>

            </MaintenanceLayout>
        );
    }

    return (
        <MaintenanceLayout title={t.layoutTitle}>
            <Head title={invoice.invoice_no} />

            <div className="mx-auto max-w-6xl space-y-6">

                {/* HEADER */}
                <section className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">

                    <div>

                        <Link
                            href="/maintenance/invoices"
                            className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 no-underline transition hover:text-slate-900"
                        >
                            <i className="bi bi-arrow-left"></i>
                            {t.back}
                        </Link>


                        <div className="mt-4 flex flex-wrap items-center gap-3">

                            <h2 className="text-3xl font-bold tracking-tight text-slate-900">
                                {invoice.invoice_no}
                            </h2>


                            <span
                                className={`
                                    inline-flex
                                    rounded-full
                                    px-3 py-1.5
                                    text-xs
                                    font-bold
                                    ${
                                        paymentClass[
                                            invoice.payment_status
                                        ] ??
                                        'bg-slate-100 text-slate-600'
                                    }
                                `}
                            >
                                {paymentText[
                                    invoice.payment_status
                                ] ??
                                    invoice.payment_status}
                            </span>

                        </div>


                        <p className="mt-2 text-sm text-slate-500">
                            {t.issuedDate}:{' '}
                            {formatDate(invoice.issued_at)}
                        </p>

                    </div>


                    <button
                        type="button"
                        onClick={handlePrint}
                        className="
                            inline-flex
                            items-center
                            justify-center
                            gap-2
                            rounded-xl
                            bg-slate-900
                            px-5 py-3
                            text-sm
                            font-semibold
                            text-white
                            shadow-lg
                            transition
                            hover:bg-slate-800
                        "
                    >
                        <i className="bi bi-printer"></i>
                        {t.print}
                    </button>

                </section>


                <div className="grid grid-cols-1 gap-6 xl:grid-cols-[minmax(0,1fr)_350px]">

                    {/* LEFT */}
                    <div className="space-y-6">

                        {/* INFO */}
                        <section className="rounded-2xl border border-slate-200 bg-white shadow-sm">

                            <div className="border-b border-slate-100 px-6 py-5">

                                <h3 className="font-bold text-slate-900">
                                    {t.invoice}
                                </h3>

                            </div>


                            <div className="grid grid-cols-1 gap-5 p-6 sm:grid-cols-2">

                                <div>

                                    <div className="text-xs font-bold uppercase tracking-wide text-slate-400">
                                        {t.requester}
                                    </div>

                                    <div className="mt-2 font-semibold text-slate-900">
                                        {invoice.request
                                            ?.requester
                                            ?.name ?? '-'}
                                    </div>

                                    <div className="mt-1 text-sm text-slate-500">
                                        {invoice.request
                                            ?.requester
                                            ?.email ?? '-'}
                                    </div>

                                </div>


                                <div>

                                    <div className="text-xs font-bold uppercase tracking-wide text-slate-400">
                                        {t.technician}
                                    </div>

                                    <div className="mt-2 font-semibold text-slate-900">
                                        {invoice.request
                                            ?.technician
                                            ?.name ?? '-'}
                                    </div>

                                </div>


                                <div>

                                    <div className="text-xs font-bold uppercase tracking-wide text-slate-400">
                                        {t.requestNo}
                                    </div>

                                    <Link
                                        href={`/maintenance/requests/${invoice.maintenance_request_id}`}
                                        className="mt-2 inline-block font-semibold text-blue-600 no-underline hover:text-blue-800"
                                    >
                                        {invoice.request
                                            ?.request_no ?? '-'}
                                    </Link>

                                </div>


                                <div>

                                    <div className="text-xs font-bold uppercase tracking-wide text-slate-400">
                                        {t.location}
                                    </div>

                                    <div className="mt-2 font-semibold text-slate-900">
                                        {invoice.request
                                            ?.location ?? '-'}
                                    </div>

                                </div>


                                <div className="sm:col-span-2">

                                    <div className="text-xs font-bold uppercase tracking-wide text-slate-400">
                                        {t.requestTitle}
                                    </div>

                                    <div className="mt-2 font-semibold text-slate-900">
                                        {invoice.request
                                            ?.title ?? '-'}
                                    </div>

                                </div>

                            </div>

                        </section>


                        {/* ITEMS */}
                        <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">

                            <div className="border-b border-slate-100 px-6 py-5">

                                <h3 className="font-bold text-slate-900">
                                    {t.invoiceDetails}
                                </h3>

                            </div>


                            <table className="w-full table-fixed">

                                <thead className="bg-slate-50">

                                    <tr>

                                        <th className="w-[46%] px-5 py-3 text-left text-xs font-bold text-slate-500">
                                            {t.description}
                                        </th>

                                        <th className="w-[14%] px-5 py-3 text-center text-xs font-bold text-slate-500">
                                            {t.quantity}
                                        </th>

                                        <th className="w-[20%] px-5 py-3 text-right text-xs font-bold text-slate-500">
                                            {t.unitPrice}
                                        </th>

                                        <th className="w-[20%] px-5 py-3 text-right text-xs font-bold text-slate-500">
                                            {t.subtotal}
                                        </th>

                                    </tr>

                                </thead>


                                <tbody className="divide-y divide-slate-100">

                                    {invoice.items?.length > 0 ? (
                                        invoice.items.map(
                                            (item) => (
                                                <tr key={item.id}>

                                                    <td className="px-5 py-4 text-sm font-medium text-slate-800">
                                                        {item.description}
                                                    </td>

                                                    <td className="px-5 py-4 text-center text-sm text-slate-600">
                                                        {item.quantity}
                                                    </td>

                                                    <td className="px-5 py-4 text-right text-sm text-slate-600">
                                                        ฿
                                                        {formatMoney(
                                                            item.unit_price
                                                        )}
                                                    </td>

                                                    <td className="px-5 py-4 text-right text-sm font-semibold text-slate-900">
                                                        ฿
                                                        {formatMoney(
                                                            item.subtotal
                                                        )}
                                                    </td>

                                                </tr>
                                            )
                                        )
                                    ) : (
                                        <>
                                            <tr>

                                                <td className="px-5 py-4 text-sm font-medium text-slate-800">
                                                    {t.laborCost}
                                                </td>

                                                <td className="px-5 py-4 text-center text-sm text-slate-600">
                                                    1
                                                </td>

                                                <td className="px-5 py-4 text-right text-sm text-slate-600">
                                                    ฿
                                                    {formatMoney(
                                                        invoice.labor_cost
                                                    )}
                                                </td>

                                                <td className="px-5 py-4 text-right text-sm font-semibold text-slate-900">
                                                    ฿
                                                    {formatMoney(
                                                        invoice.labor_cost
                                                    )}
                                                </td>

                                            </tr>


                                            <tr>

                                                <td className="px-5 py-4 text-sm font-medium text-slate-800">
                                                    {t.partsCost}
                                                </td>

                                                <td className="px-5 py-4 text-center text-sm text-slate-600">
                                                    1
                                                </td>

                                                <td className="px-5 py-4 text-right text-sm text-slate-600">
                                                    ฿
                                                    {formatMoney(
                                                        invoice.parts_cost
                                                    )}
                                                </td>

                                                <td className="px-5 py-4 text-right text-sm font-semibold text-slate-900">
                                                    ฿
                                                    {formatMoney(
                                                        invoice.parts_cost
                                                    )}
                                                </td>

                                            </tr>
                                        </>
                                    )}

                                </tbody>

                            </table>

                        </section>


                        {/* NOTE */}
                        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">

                            <div className="text-xs font-bold uppercase tracking-wide text-slate-400">
                                {t.note}
                            </div>

                            <div className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-700">
                                {invoice.note || t.noNote}
                            </div>

                        </section>

                    </div>


                    {/* RIGHT */}
                    <div className="space-y-6">

                        {/* SUMMARY */}
                        <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">

                            <h3 className="font-bold text-slate-900">
                                {t.summary}
                            </h3>


                            <div className="mt-5 space-y-3">

                                <div className="flex items-center justify-between text-sm">

                                    <span className="text-slate-500">
                                        {t.laborCost}
                                    </span>

                                    <span className="font-semibold text-slate-900">
                                        ฿
                                        {formatMoney(
                                            invoice.labor_cost
                                        )}
                                    </span>

                                </div>


                                <div className="flex items-center justify-between text-sm">

                                    <span className="text-slate-500">
                                        {t.partsCost}
                                    </span>

                                    <span className="font-semibold text-slate-900">
                                        ฿
                                        {formatMoney(
                                            invoice.parts_cost
                                        )}
                                    </span>

                                </div>


                                <div className="border-t border-slate-200 pt-4">

                                    <div className="flex items-end justify-between gap-3">

                                        <span className="font-bold text-slate-900">
                                            {t.totalAmount}
                                        </span>

                                        <span className="text-2xl font-bold text-slate-900">
                                            ฿
                                            {formatMoney(
                                                invoice.total_amount
                                            )}
                                        </span>

                                    </div>

                                </div>

                            </div>

                        </section>


                        {/* PAYMENT STATUS: เปลี่ยนเป็นชำระแล้วอัตโนมัติเมื่อผู้แจ้งชำระเงินผ่านระบบ */}
                        <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">

                            <div className="flex items-center gap-3">

                                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600">
                                    <i className="bi bi-credit-card"></i>
                                </div>

                                <h3 className="font-bold text-slate-900">
                                    {t.paymentStatus}
                                </h3>

                            </div>

                            <div className={`mt-5 rounded-xl px-4 py-3 text-sm font-semibold ${paymentClass[invoice.payment_status] ?? ''}`}>
                                {paymentText[invoice.payment_status] ?? invoice.payment_status}
                            </div>

                            {invoice.payment_status === 'paid' && (
                                <dl className="mt-4 space-y-2 text-sm">
                                    <div className="flex justify-between gap-3">
                                        <dt className="text-slate-500">{t.paidAt}</dt>
                                        <dd className="font-semibold text-slate-900">
                                            {invoice.paid_at
                                                ? new Date(invoice.paid_at).toLocaleString(language === 'en' ? 'en-US' : 'th-TH', { dateStyle: 'medium', timeStyle: 'short' })
                                                : '-'}
                                        </dd>
                                    </div>
                                    <div className="flex justify-between gap-3">
                                        <dt className="text-slate-500">{t.method}</dt>
                                        <dd className="font-semibold text-slate-900">{t[invoice.payment_method] ?? invoice.payment_method ?? '-'}</dd>
                                    </div>
                                    <div className="flex justify-between gap-3">
                                        <dt className="text-slate-500">{t.reference}</dt>
                                        <dd className="font-semibold text-slate-900">{invoice.payment_ref ?? '-'}</dd>
                                    </div>
                                </dl>
                            )}

                            {invoice.payment_status === 'unpaid' && (
                                <>
                                    <p className="mt-4 text-sm leading-6 text-slate-500">
                                        {t.awaitingPayment}
                                    </p>

                                    {(isAdmin || invoice.request?.user_id === user.id) && (
                                        <Link
                                            href={`/maintenance/invoices/${invoice.id}/pay`}
                                            className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-600 px-4 py-3 text-sm font-semibold text-white no-underline transition hover:bg-emerald-700"
                                        >
                                            <i className="bi bi-wallet2"></i>
                                            {t.payNow}
                                        </Link>
                                    )}

                                    {isAdmin && (
                                        <button
                                            type="button"
                                            disabled={updating}
                                            onClick={cancelInvoice}
                                            className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700 transition hover:bg-rose-100 disabled:cursor-not-allowed disabled:opacity-60"
                                        >
                                            <i className="bi bi-x-circle"></i>
                                            {updating ? t.saving : t.cancelInvoice}
                                        </button>
                                    )}
                                </>
                            )}

                        </section>


                        {/* PRINT */}
                        <section className="rounded-2xl bg-gradient-to-br from-slate-900 to-blue-950 p-5 text-white shadow-xl">

                            <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/10">
                                <i className="bi bi-printer text-lg"></i>
                            </div>

                            <h3 className="mt-4 font-bold">
                                {t.print}
                            </h3>

                            <p className="mt-2 text-sm leading-6 text-slate-300">
                                {t.invoiceNo}: {invoice.invoice_no}
                            </p>


                            <button
                                type="button"
                                onClick={handlePrint}
                                className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-bold text-slate-900 transition hover:bg-slate-100"
                            >
                                <i className="bi bi-printer"></i>
                                {t.print}
                            </button>

                        </section>

                    </div>

                </div>

            </div>
        </MaintenanceLayout>
    );
}